---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Add EC2 instance as host
      ansible.builtin.add_host:
        name: '{{ target }}'
        groups: ec2
        ansible_user: '{{ user }}'

- name: Run the changes on the EC2 instance
  hosts: ec2
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ identity_file }}'
  gather_facts: false
  tasks:
    - include_role:
        name: changes